### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by grossga** [mddub/minimed-connect-to-nightscout#3]
Since about 9:15 PST on 5/9/2016, I am getting the following error within Nightscout when the MMCONNECT_VERBOSE=true environment variable is enabled.  Before this everything was working as expected for the last 2 weeks.:

Mon May 09 2016 22:33:31 GMT-0700 (PDT) Logging in to CareLink
Mon May 09 2016 22:33:31 GMT-0700 (PDT) POST https://carelink.minimed.com/patient/j_security_check
MiniMed Connect error: Error: unable to verify the first certificate

I am not certain what is wrong, and this may be a red herring but in the authentication POST in carelink.js it doesn't look like the j_character_encoding key=UTF-8 is being sent.  When attempting to mimick the login using POSTMAN, I was unable to authenticate without this value in the payload.

**Comment by mddub** [comment]
Thanks for posting! Some reports from CGM in the Cloud suggest that this fixed itself this morning... can you confirm?

**Comment by grossga** [comment]
Yes, the issue looks to have corrected itself sometime during the night of 5/10.
