### ISSUE TITLE
Guardian Connect

### ISSUE THREAD

**Issue by Schoggiweggli** [mddub/minimed-connect-to-nightscout#4]
The european Version of Minimed Connect is released now. 

The device is called Guardian Conenct and there is a Minimed Connect tab in Carelink. It works similar to the US Minimed Conenct but it does not work with nightscout because the URLs are different i suppose.

Would be great if there is a way to get it working with carelink.minimed.eu

**Comment by mddub** [comment]
Cool, thanks for reporting! Pull requests are very welcome.

**Comment by Schoggiweggli** [comment]
Well, i would like to help but i am not a programmer, just a tech savvy user.

I'm afraid i am not very helpful. Although i have a Guardian Connect device in use, the only thing i could do is to deploy it to Heroku to test if it is working, after necessary changes have been made.

**Comment by bogdangorescu** [comment]
You can replace the authentication server in US with the one on the EU, by modifying the corresponding strings in node_modules/minimed-connect-to-nightscout/carelink.js

But this won't solve the issue! After fixing this first error, a second error occurs that has something to do with time interval. 
Here's the log:
`RangeError: Invalid time value at timestampAsString (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:23:30) at deviceStatusEntry (/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:66:16) at Object.module.exports [as transform] 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/transform.js:129:20) at handleCarelinkData 

(/nfs/VM3/10000_medtronic/lib/plugins/mmconnect.js:55:33) at next 

(/nfs/VM3/10000_medtronic/node_modules/common/index.js:138:6) at Object.parseData 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:137:5) at next 

(/nfs/VM3/10000_medtronic/node_modules/common/index.js:138:6) at Request.<anonymous> 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:124:11) at Request._callback 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/carelink.js:55:8) at Request.self.callback 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:198:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:1063:14) at emitOne (events.js:101:20) at Request.emit (events.js:188:7) at Gunzip.<anonymous> 

(/nfs/VM3/10000_medtronic/node_modules/minimed-connect-to-nightscout/node_modules/request/request.js:1009:12) at emitNone (events.js:91:20) at Gunzip.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)`

**Comment by Schoggiweggli** [comment]
resolved, see issue #2
